namespace Adam
{
    public partial class AdamGame
    {
        /// <summary>
        /// Each type of tile has its own unique ID.
        /// </summary>
        public enum TileType : int
        {
            Air = 0,
            Grass = 1,
            Stone = 2,
            MarbleFloor = 3,
            Hellrock = 4,
            Sand = 5,
            Mesa = 6,
            ShortGrass = 7,
            Metal = 8,
            TallGrass = 9,
            GoldBrick = 10,
            Torch = 11,
            Chandelier = 12,
            Door = 13,
            Vine,
            Ladder,
            Chain,
            Flower,
            MarbleColumn,
            Chest,
            MarbleBrick,
            Scaffolding,
            Spikes,
            Water,
            Lava,
            Poison,
            GoldenApple,
            GoldenChest,
            HealthApple,
            MarbleCeiling,
            Tree = 31,
            SmallRock,
            BigRock,
            MediumRock,
            Pebbles,
            Sign,
            Checkpoint,
            StoneBrick,
            Snow,
            SnowyGrass,
            CompressedVoid,
            FlameSpitter,
            MachineGun,
            Cactus,
            MushroomBooster,
            VoidLadder,
            WoodenPlatform,
            AquaantCrystal,
            HeliauraCrystal,
            SentistractSludge,
            VoidFireSpitter,
            SapphireCrystal,
            RubyCrystal,
            EmeraldCrystal,
            Skull,
            Stalagmite,
            Mud,
            BackgroundDoor,
            Bed,
            Bookshelf,
            Painting,
            TreeofKnowledge,
            TreeBark,
            PlayerDetector,
            Teleporter,
            Wood,
            Glass,
            SteelBeam,
            SnowCover,
            Mosaic,
            MosaicVase,
            MushroomDecor,


            GoldBrickWall = 100,
            StoneWall,
            DirtWall,
            Fence,
            MarbleWall,
            SandWall,
            HellstoneWall,
            StoneBrickWall,
            MesaWall,
            RedWallpaper,
            Nothing,
            TreeOfKnowledge,
            LightYellowPaint,

            Player = 200,
            Snake,
            Frog,
            NPC,
            Lost,
            Hellboar,
            FallingBoulder,
            Bat,
            Duck,
            BeingofSight
        }

    }
}
